version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      DB_URL: postgresql://app:pass@db:5432/orders
    depends_on:
      - db

volumes:
  dbdata:
